/**
 * Single source of truth for user-facing Hebrew copy (Kursim-style convention).
 * No hardcoded strings in components — add keys here.
 */
export const he = {
  appName: "קשר",
  tagline: "בוט וואטסאפ שאוסף לידים וקובע פגישות מכירה",

  // auth
  login: "התחברות",
  register: "הרשמה",
  logout: "התנתקות",
  email: "אימייל",
  password: "סיסמה",
  orgName: "שם העסק",
  yourName: "השם שלך",
  loginCta: "התחבר",
  registerCta: "צור חשבון",
  haveAccount: "כבר יש לך חשבון?",
  noAccount: "אין לך חשבון עדיין?",
  authError: "האימייל או הסיסמה שגויים",
  emailTaken: "האימייל כבר רשום במערכת",

  // dashboard
  dashboard: "לוח בקרה",
  connections: "חיבורי וואטסאפ",
  flows: "בוטים (תסריטים)",
  leads: "לידים",
  appointments: "פגישות",
  welcome: "ברוך הבא",
  phase0Note:
    "שלד ראשוני (Phase 0) פעיל. השלב הבא: חיבור מספר וואטסאפ אמיתי (Phase 1).",

  // connections
  connectionsTitle: "חיבורי וואטסאפ",
  connectionsSubtitle: "חבר/י מספר וואטסאפ כדי שהבוט יתחיל לענות ללידים",
  addConnection: "הוסף חיבור",
  connectionLabel: "כינוי לחיבור (למשל: קו מכירות)",
  create: "צור",
  scanQr: "סרוק/י את הקוד באפליקציית וואטסאפ ← מכשירים מקושרים ← קישור מכשיר",
  waiting: "ממתין לקוד…",
  connect: "חבר",
  reconnect: "חבר מחדש",
  disconnect: "נתק",
  backToDashboard: "→ חזרה ללוח הבקרה",
  noConnections: "עדיין אין חיבורים. הוסף/י אחד כדי להתחיל.",
  statusLabel: {
    PENDING: "ממתין",
    QR: "ממתין לסריקה",
    CONNECTED: "מחובר",
    DISCONNECTED: "מנותק",
    LOGGED_OUT: "נותק מהמכשיר",
  },

  // leads / CRM
  leadsTitle: "לידים",
  leadsSubtitle: "כל מי שכתב לבוט — עם התשובות שנאספו",
  searchLeads: "חיפוש לפי שם או טלפון…",
  noLeads: "עדיין אין לידים. ברגע שמישהו יכתוב לבוט הוא יופיע כאן.",
  colName: "שם",
  colPhone: "טלפון",
  colTags: "תגיות",
  colCreated: "נוצר",
  colFields: "תשובות",
  backToLeads: "→ חזרה ללידים",
  leadDetails: "פרטי ליד",
  collectedFields: "תשובות שנאספו",
  transcript: "שיחה",
  noMessages: "אין הודעות עדיין",
  appointmentsTitle: "פגישות",
  appointmentsSubtitle: "פגישות מכירה שנקבעו דרך הבוט",
  noAppointments: "אין פגישות",
  upcoming: "הקרובות",
  past: "עברו",
  msgIn: "ליד",
  msgOut: "בוט",

  // settings / integrations
  settings: "הגדרות",
  settingsTitle: "הגדרות ואינטגרציות",
  googleCalendar: "יומן Google",
  googleCalendarDesc: "סנכרון דו־כיווני: פגישות שנקבעות ייווצרו ביומן, ושעות תפוסות יחסמו מהצעת מועדים.",
  connectGoogle: "חבר/י יומן Google",
  disconnectGoogle: "נתק יומן",
  googleConnected: "יומן Google מחובר ✅",
  googleNotConfigured: "אינטגרציית Google לא הוגדרה בשרת (חסר GOOGLE_CLIENT_ID/SECRET).",
  googleConnectedMsg: "היומן חובר בהצלחה!",
  googleErrorMsg: "החיבור נכשל, נסה/י שוב.",
  remindersTitle: "תזכורות",
  remindersDesc: "לפני כל פגישה נשלחות ללקוח תזכורות אוטומטיות בוואטסאפ (24 שעות ושעה לפני).",

  // billing / plans
  billing: "מנוי ותשלום",
  billingTitle: "בחירת מסלול",
  currentPlan: "המסלול הנוכחי",
  perMonth: "לחודש",
  free: "חינם",
  choosePlan: "בחר/י מסלול",
  upgrade: "שדרג/י",
  growNotConfigured: "כדי לגבות תשלום צריך קודם לחבר את חשבון Grow שלך (ראה/י אשף ההקמה).",
  goToOnboarding: "לאשף ההקמה",

  // secrets (secure paste)
  secretsTitle: "מפתחות סודיים (Grow)",
  secretsDesc: "המפתחות נשמרים מוצפנים בשרת (AES-256). לעולם לא נציג אותם שוב — רק 4 הספרות האחרונות.",
  growPageCode: "קוד עמוד (Page Code)",
  growUserId: "מזהה משתמש (User ID)",
  growApiKey: "מפתח API (אופציונלי)",
  saveSecret: "שמור מאובטח",
  secretSaved: "נשמר מוצפן ✅",
  secretSet: "מוגדר",
  secretNotSet: "לא הוגדר",
  removeSecret: "הסר",
  howToGetGrow: "איך משיגים את המפתחות?",
  growStep1: "היכנס/י לחשבון Grow שלך בכתובת grow.business ← הגדרות ← מפתחות / API.",
  growStep2: "העתק/י את \"קוד העמוד\" (Page Code) ואת \"מזהה המשתמש\" (User ID).",
  growStep3: "הדבק/י אותם כאן למטה ולחצ/י \"שמור מאובטח\". המפתחות מוצפנים ואינם נחשפים.",

  // onboarding
  onboarding: "אשף הקמה",
  onboardingTitle: "בואו נחבר את מערכת קביעת הפגישות שלך",
  onboardingIntro: "3 שלבים קצרים כדי שהבוט יתחיל לקבוע פגישות מכירה בוואטסאפ.",
  stepDone: "בוצע",
  stepTodo: "לביצוע",
  ob1Title: "1. חיבור מספר וואטסאפ",
  ob1Desc: "חבר/י את המספר שדרכו הלקוחות כותבים אליך.",
  ob1Cta: "לחיבור וואטסאפ",
  ob2Title: "2. הגדרת שעות פנויות",
  ob2Desc: "המערכת מציעה ללקוח מועדים פנויים לפי הזמינות שלך (כרגע: א׳–ה׳ 09:00–17:00).",
  ob3Title: "3. חיבור תשלום (Grow) — אופציונלי",
  ob3Desc: "רק אם תרצה/י לגבות תשלום עבור המנוי. הדבק/י את מפתחות Grow באופן מאובטח.",
  obFinish: "סיום — למרכז הבקרה",
  obConnected: "מחובר ✅",

  // flows
  flowsTitle: "בוטים (תסריטים)",
  flowsSubtitle: "התסריטים שהבוט מריץ מול לידים",
  noFlows: "אין תסריטים עדיין",
  active: "פעיל",
  inactive: "כבוי",
  colVersion: "גרסה",
  colSteps: "שלבים",
  editFlow: "עריכה",
  newFlow: "תסריט חדש",
  activate: "הפעל",
  deactivate: "כבה",
  backToFlows: "→ חזרה לתסריטים",

  // flow builder — trigger
  triggerTitle: "מתי הבוט מתחיל? (טריגר)",
  triggerDesc: "כל שיחה מתחילה מהודעה של הלקוח. בחר/י מה מפעיל את התסריט הזה.",
  triggerAny: "כל הודעה ראשונה",
  triggerKeyword: "מילות מפתח",
  triggerKeywordsLabel: "מילים שיפעילו (מופרדות בפסיק)",
  triggerKeywordsHint: "לדוגמה: מעוניין, פגישה, מחיר",

  // flow builder
  saveFlow: "שמור תסריט",
  saved: "נשמר ✅",
  saveError: "שגיאה",
  selectNode: "בחר/י שלב לעריכה",
  startNode: "שלב התחלה",
  endNode: "סיום",
  deleteNode: "מחק שלב",
  fMessage: "טקסט ההודעה",
  fPrompt: "טקסט השאלה",
  fField: "שם השדה (לשמירה)",
  fExpect: "סוג תשובה",
  fChoices: "אפשרויות (מופרדות בפסיק)",
  fWhen: "תנאי",
  fThen: "אם כן →",
  fElse: "אם לא →",
  fAction: "פעולה",
  fNext: "השלב הבא →",
} as const;

export type HeKey = keyof typeof he;
