/**
 * Single source of truth for user-facing Hebrew copy (Kursim-style convention).
 * No hardcoded strings in components — add keys here.
 */
export const he = {
  appName: "קשר",
  tagline: "בוט וואטסאפ שאוסף לידים וקובע פגישות מכירה",

  // auth
  login: "התחברות",
  register: "הרשמה",
  logout: "התנתקות",
  email: "אימייל",
  password: "סיסמה",
  orgName: "שם העסק",
  yourName: "השם שלך",
  loginCta: "התחבר",
  registerCta: "צור חשבון",
  haveAccount: "כבר יש לך חשבון?",
  noAccount: "אין לך חשבון עדיין?",
  authError: "האימייל או הסיסמה שגויים",
  emailTaken: "האימייל כבר רשום במערכת",

  // dashboard
  dashboard: "סקירה",
  connections: "חיבורי וואטסאפ",
  flows: "בוטים (תסריטים)",
  leads: "לידים",
  appointments: "פגישות",
  welcome: "ברוך הבא",

  // overview / analytics
  overviewHi: "שלום",
  overviewSub: "הנה מה שקורה בעסק שלך כרגע",
  kpiLeads: "סה״כ לידים",
  kpiLeads7: "לידים השבוע",
  kpiAppointments: "פגישות מתוכננות",
  kpiCompletion: "שיחות שהושלמו",
  leadsOverTime: "לידים ב-14 הימים האחרונים",
  topServices: "נושאים מובילים",
  recentLeads: "לידים אחרונים",
  viewAll: "הצג הכל",
  setupTitle: "נגמר ההקמה? בואו נתחיל",
  setupBody: "חבר/י מספר וואטסאפ והבוט יתחיל לאסוף לידים אוטומטית.",
  setupCta: "לאשף ההקמה",
  noData: "אין נתונים עדיין",

  // admin
  adminPanel: "ניהול פלטפורמה",
  adminTitle: "ניהול פלטפורמה",
  adminSubtitle: "כל העסקים, המנויים והתשלומים במקום אחד",
  adminOrgs: "עסקים",
  adminUsers: "משתמשים",
  adminActivePlans: "מנויים בתשלום",
  adminOrgsTable: "רשימת עסקים",
  colOrg: "עסק",
  colPlan: "מסלול",
  colUsersCount: "משתמשים",
  colLeadsCount: "לידים",
  colJoined: "הצטרפו",
  setPlan: "עדכן מסלול",
  unlock: "פתח מסלול",
  genLink: "צור קישור תשלום",
  paymentLink: "קישור תשלום",
  copyLink: "העתק",
  platformGrow: "הגדרות תשלום (Grow) — פלטפורמה",
  platformGrowDesc: "מפתחות Grow ברמת הפלטפורמה. רק אתה (מנהל-על) רואה זאת. לקוחות אינם נחשפים לתשלום.",
  backToApp: "→ לאזור הלקוח",

  // bot readiness status
  statusLive: "הבוט פעיל ועונה ללקוחות",
  statusLiveHint: "שלח/י הודעת בדיקה למספר המחובר כדי לראות את הבוט בפעולה.",
  statusNoNumber: "אין מספר וואטסאפ מחובר",
  statusNoNumberHint: "חבר/י מספר (סריקת QR) כדי שהבוט יתחיל לעבוד.",
  statusNoFlow: "מחובר — אבל אין בוט פעיל",
  statusNoFlowHint: "הפעל/י תסריט כדי שהבוט יתחיל לענות ללקוחות.",
  statusConnectNumber: "לחיבור מספר",
  statusActivateFlow: "להפעלת בוט",
  statusTestNumber: "שלח/י הודעת בדיקה אל",

  // connections
  connectionsTitle: "חיבורי וואטסאפ",
  connectionsSubtitle: "חבר/י מספר וואטסאפ כדי שהבוט יתחיל לענות ללידים",
  addConnection: "הוסף חיבור",
  connectionLabel: "כינוי לחיבור (למשל: קו מכירות)",
  create: "צור",
  scanQr: "סרוק/י את הקוד באפליקציית וואטסאפ ← מכשירים מקושרים ← קישור מכשיר",
  waiting: "ממתין לקוד…",
  connect: "חבר",
  reconnect: "חבר מחדש",
  disconnect: "נתק",
  backToDashboard: "→ חזרה ללוח הבקרה",
  noConnections: "עדיין אין חיבורים. הוסף/י אחד כדי להתחיל.",
  statusLabel: {
    PENDING: "ממתין",
    QR: "ממתין לסריקה",
    CONNECTED: "מחובר",
    DISCONNECTED: "מנותק",
    LOGGED_OUT: "נותק מהמכשיר",
  },

  // cloud api (official WhatsApp)
  providerBaileys: "חיבור מהיר (QR)",
  providerCloud: "WhatsApp רשמי (Cloud API)",
  cloudDesc: "החיבור הרשמי של Meta — יציב ומאושר לשימוש עסקי בקנה מידה. דורש חשבון WhatsApp Business.",
  cloudPhoneId: "Phone Number ID",
  cloudToken: "Access Token (מוצפן)",
  cloudVerify: "Verify Token (אופציונלי — ייווצר אוטומטית)",
  cloudCreate: "חבר Cloud API",
  cloudWebhookTitle: "כתובת Webhook להגדרה ב-Meta",
  cloudWebhookHint: "הדבק/י את הכתובת הזו + ה-Verify Token בהגדרות ה-Webhook של אפליקציית ה-Meta שלך.",
  cloudViaLabel: "רשמי (Cloud API)",

  // leads / CRM
  leadsTitle: "לידים",
  leadsSubtitle: "כל מי שכתב לבוט — עם התשובות שנאספו",
  searchLeads: "חיפוש לפי שם או טלפון…",
  noLeads: "עדיין אין לידים. ברגע שמישהו יכתוב לבוט הוא יופיע כאן.",
  colName: "שם",
  colPhone: "טלפון",
  colTags: "תגיות",
  colCreated: "נוצר",
  colFields: "תשובות",
  backToLeads: "→ חזרה ללידים",
  leadDetails: "פרטי ליד",
  collectedFields: "תשובות שנאספו",
  transcript: "שיחה",
  noMessages: "אין הודעות עדיין",
  appointmentsTitle: "פגישות",
  appointmentsSubtitle: "פגישות מכירה שנקבעו דרך הבוט",
  noAppointments: "אין פגישות",
  upcoming: "הקרובות",
  past: "עברו",
  msgIn: "ליד",
  msgOut: "בוט",

  // settings / integrations
  settings: "הגדרות",
  settingsTitle: "הגדרות ואינטגרציות",
  googleCalendar: "יומן Google",
  googleCalendarDesc: "סנכרון דו־כיווני: פגישות שנקבעות ייווצרו ביומן, ושעות תפוסות יחסמו מהצעת מועדים.",
  connectGoogle: "חבר/י יומן Google",
  disconnectGoogle: "נתק יומן",
  googleConnected: "יומן Google מחובר ✅",
  googleNotConfigured: "אינטגרציית Google לא הוגדרה בשרת (חסר GOOGLE_CLIENT_ID/SECRET).",
  googleConnectedMsg: "היומן חובר בהצלחה!",
  googleErrorMsg: "החיבור נכשל, נסה/י שוב.",
  remindersTitle: "תזכורות",
  remindersDesc: "לפני כל פגישה נשלחות ללקוח תזכורות אוטומטיות בוואטסאפ (24 שעות ושעה לפני).",

  // billing / plans
  billing: "מנוי ותשלום",
  billingTitle: "בחירת מסלול",
  currentPlan: "המסלול הנוכחי",
  perMonth: "לחודש",
  free: "חינם",
  choosePlan: "בחר/י מסלול",
  upgrade: "שדרג/י",
  growNotConfigured: "כדי לגבות תשלום צריך קודם לחבר את חשבון Grow שלך (ראה/י אשף ההקמה).",
  goToOnboarding: "לאשף ההקמה",

  // secrets (secure paste)
  secretsTitle: "מפתחות סודיים (Grow)",
  secretsDesc: "המפתחות נשמרים מוצפנים בשרת (AES-256). לעולם לא נציג אותם שוב — רק 4 הספרות האחרונות.",
  growPageCode: "קוד עמוד (Page Code)",
  growUserId: "מזהה משתמש (User ID)",
  growApiKey: "מפתח API (אופציונלי)",
  saveSecret: "שמור מאובטח",
  secretSaved: "נשמר מוצפן ✅",
  secretSet: "מוגדר",
  secretNotSet: "לא הוגדר",
  removeSecret: "הסר",
  howToGetGrow: "איך משיגים את המפתחות?",
  growStep1: "היכנס/י לחשבון Grow שלך בכתובת grow.business ← הגדרות ← מפתחות / API.",
  growStep2: "העתק/י את \"קוד העמוד\" (Page Code) ואת \"מזהה המשתמש\" (User ID).",
  growStep3: "הדבק/י אותם כאן למטה ולחצ/י \"שמור מאובטח\". המפתחות מוצפנים ואינם נחשפים.",

  // onboarding
  onboarding: "אשף הקמה",
  onboardingTitle: "בואו נחבר את מערכת קביעת הפגישות שלך",
  onboardingIntro: "3 שלבים קצרים כדי שהבוט יתחיל לקבוע פגישות מכירה בוואטסאפ.",
  stepDone: "בוצע",
  stepTodo: "לביצוע",
  ob1Title: "1. חיבור מספר וואטסאפ",
  ob1Desc: "חבר/י את המספר שדרכו הלקוחות כותבים אליך.",
  ob1Cta: "לחיבור וואטסאפ",
  ob2Title: "2. הגדרת שעות פנויות",
  ob2Desc: "המערכת מציעה ללקוח מועדים פנויים לפי הזמינות שלך (כרגע: א׳–ה׳ 09:00–17:00).",
  ob3Title: "3. סנכרון יומן Google — אופציונלי",
  ob3Desc: "חבר/י יומן Google כדי שפגישות ייווצרו אוטומטית ושעות תפוסות ייחסמו.",
  ob3Cta: "לחיבור יומן",
  obFinish: "סיום — למרכז הבקרה",
  obConnected: "מחובר ✅",
  obHowItWorks: "איך זה עובד?",
  obFlow1: "לקוח שולח הודעה למספר שלך",
  obFlow2: "הבוט מזהה טריגר ומתחיל תסריט",
  obFlow3: "הבוט אוסף תשובות וקובע פגישה",
  obFlow4: "הכול מופיע מסודר בלוח הבקרה שלך",

  // flows
  flowsTitle: "בוטים (תסריטים)",
  flowsSubtitle: "התסריטים שהבוט מריץ מול לידים",
  noFlows: "אין תסריטים עדיין",
  active: "פעיל",
  inactive: "כבוי",
  colVersion: "גרסה",
  colSteps: "שלבים",
  editFlow: "עריכה",
  newFlow: "תסריט חדש",
  activate: "הפעל",
  deactivate: "כבה",
  backToFlows: "→ חזרה לתסריטים",

  // flow builder — trigger
  triggerTitle: "מתי הבוט מתחיל? (טריגר)",
  triggerDesc: "כל שיחה מתחילה מהודעה של הלקוח. בחר/י מה מפעיל את התסריט הזה.",
  triggerAny: "כל הודעה ראשונה",
  triggerKeyword: "מילות מפתח",
  triggerKeywordsLabel: "מילים שיפעילו (מופרדות בפסיק)",
  triggerKeywordsHint: "לדוגמה: מעוניין, פגישה, מחיר",
  startNodeTitle: "התחלה",
  startNodeAny: "מתחיל בכל הודעה",
  startNodeKeyword: "מתחיל אם ההודעה מכילה:",

  // flow builder — node kinds & help
  nodeKindMessage: "הודעה",
  nodeKindQuestion: "שאלה",
  nodeKindCondition: "תנאי",
  nodeKindAction: "פעולה",
  nodeDescMessage: "שולח טקסט ללקוח (בלי לחכות לתשובה)",
  nodeDescQuestion: "שואל שאלה ושומר את התשובה בכרטיס הליד",
  nodeDescCondition: "מפצל את המסלול לפי תשובה (כן / לא)",
  nodeDescAction: "מבצע פעולה: קביעת פגישה, התראה, תגית ועוד",
  addStep: "הוסף שלב",
  savesTo: "💾 נשמר לשדה",
  dragHint: "💡 גרור/י מנקודת החיבור בתחתית שלב אל שלב אחר כדי לחבר ביניהם",
  questionSaveHint: "התשובה של הלקוח תישמר בכרטיס הליד תחת שם השדה הזה ותופיע ב-CRM.",
  chooseWhatToAsk: "מה לשאול את הלקוח?",
  chooseFieldName: "לאיזה שדה לשמור? (למשל: name, phone, budget)",
  chooseAnswerType: "סוג התשובה הצפויה",
  chooseAction: "איזו פעולה לבצע?",

  // sequence builder (step-by-step)
  seqIntro: "בנה/י את השיחה שלב אחרי שלב. ככה היא תיראה ללקוח ←",
  seqEmpty: "עוד אין שלבים. הוסף/י את השלב הראשון 👇",
  addStepMenu: "הוסף שלב",
  stepMessageLabel: "הודעה",
  stepQuestionLabel: "שאלה",
  stepBookLabel: "קביעת פגישה",
  stepMessageDesc: "הבוט שולח הודעה (למשל: קישור ליומן)",
  stepQuestionDesc: "הבוט שואל שאלה ושומר את התשובה",
  stepBookDesc: "הבוט מציע ללקוח מועדים פנויים לפגישה",
  botSends: "הבוט שולח:",
  botAsks: "הבוט שואל:",
  saveAnswerTo: "שומר את התשובה בשדה (יופיע ב-CRM):",
  answerTypeLabel: "סוג התשובה",
  choicesLabel: "כפתורי בחירה (אופציונלי, מופרד בפסיק)",
  bookNote: "הבוט יציע אוטומטית מועדים פנויים לפי הזמינות שלך, יקבע פגישה וישלח אישור.",
  msgPlaceholder: "כתוב/י מה הבוט יאמר…",
  askPlaceholder: "מה לשאול את הלקוח?",
  fieldPlaceholder: "לדוגמה: name, city, budget",
  previewTitle: "תצוגה מקדימה",
  previewYouAnswer: "התשובה שלי…",
  moveUp: "למעלה",
  moveDown: "למטה",
  stepN: "שלב",
  whenStarts: "מתי השיחה מתחילה?",

  // flow builder
  saveFlow: "שמור והפעל",
  saved: "נשמר ✅",
  savedLive: "נשמר — הבוט פעיל ועונה ללקוחות! ✅",
  flowLive: "🟢 פעיל — הבוט עונה ללקוחות",
  flowOff: "⚪ כבוי — שמור/י כדי להפעיל את הבוט",
  saveError: "שגיאה",
  selectNode: "בחר/י שלב לעריכה",
  startNode: "שלב התחלה",
  endNode: "סיום",
  deleteNode: "מחק שלב",
  fMessage: "טקסט ההודעה",
  fPrompt: "טקסט השאלה",
  fField: "שם השדה (לשמירה)",
  fExpect: "סוג תשובה",
  fChoices: "אפשרויות (מופרדות בפסיק)",
  fWhen: "תנאי",
  fThen: "אם כן →",
  fElse: "אם לא →",
  fAction: "פעולה",
  fNext: "השלב הבא →",
} as const;

export type HeKey = keyof typeof he;
