/**
 * Single source of truth for user-facing Hebrew copy (Kursim-style convention).
 * No hardcoded strings in components — add keys here.
 */
export const he = {
  appName: "GeniriBot",
  tagline: "בוט וואטסאפ חכם שאוסף לידים וקובע פגישות — אוטומטית",

  // auth
  login: "התחברות",
  register: "הרשמה",
  logout: "התנתקות",
  email: "אימייל",
  password: "סיסמה",
  orgName: "שם העסק",
  yourName: "השם שלך",
  loginCta: "התחבר",
  registerCta: "צור חשבון",
  haveAccount: "כבר יש לך חשבון?",
  noAccount: "אין לך חשבון עדיין?",
  authError: "האימייל או הסיסמה שגויים",
  emailTaken: "האימייל כבר רשום במערכת",

  // dashboard
  dashboard: "סקירה",
  connections: "חיבורי וואטסאפ",
  flows: "בוטים (תסריטים)",
  leads: "לידים",
  appointments: "פגישות",
  welcome: "ברוך הבא",

  // overview / analytics
  overviewHi: "שלום",
  overviewSub: "הנה מה שקורה בעסק שלך כרגע",
  kpiLeads: "סה״כ לידים",
  kpiLeads7: "לידים השבוע",
  kpiAppointments: "פגישות מתוכננות",
  kpiCompletion: "שיחות שהושלמו",
  leadsOverTime: "לידים ב-14 הימים האחרונים",
  topServices: "נושאים מובילים",
  recentLeads: "לידים אחרונים",
  viewAll: "הצג הכל",
  setupTitle: "נגמר ההקמה? בואו נתחיל",
  setupBody: "חבר/י מספר וואטסאפ והבוט יתחיל לאסוף לידים אוטומטית.",
  setupCta: "לאשף ההקמה",
  noData: "אין נתונים עדיין",

  // admin
  adminPanel: "ניהול פלטפורמה",
  adminTitle: "ניהול פלטפורמה",
  adminSubtitle: "כל העסקים, המנויים והתשלומים במקום אחד",
  adminOrgs: "עסקים",
  adminUsers: "משתמשים",
  adminActivePlans: "מנויים בתשלום",
  adminOrgsTable: "רשימת עסקים",
  colOrg: "עסק",
  colPlan: "מסלול",
  colUsersCount: "משתמשים",
  colLeadsCount: "לידים",
  colJoined: "הצטרפו",
  setPlan: "עדכן מסלול",
  unlock: "פתח מסלול",
  genLink: "צור קישור תשלום",
  paymentLink: "קישור תשלום",
  copyLink: "העתק",
  platformGrow: "הגדרות תשלום (Grow) — פלטפורמה",
  platformGrowDesc: "מפתחות Grow ברמת הפלטפורמה. רק אתה (מנהל-על) רואה זאת. לקוחות אינם נחשפים לתשלום.",
  platformPaymentUrl: "קישור לעמוד תשלום (Grow)",
  platformPaymentUrlDesc: "הקישור לעמוד התשלום הסטטי שהוקם ב-Grow (עם שני המסלולים). דף הנחיתה ועמוד \"בחירת מסלול\" מפנים לכאן כל עוד החיוב האוטומטי דרך ה-API לא מוגדר.",
  platformPaymentUrlPlaceholder: "https://pay.grow.link/...",
  backToApp: "→ לאזור הלקוח",

  // platform Meta / Embedded Signup config
  platformMeta: "הגדרות WhatsApp רשמי (Meta) — פלטפורמה",
  platformMetaDesc: "פרטי אפליקציית ה-Meta ל-Embedded Signup. ברגע שמוגדרים, לקוחות יראו את כפתור \"התחברות עם פייסבוק\" בעמוד החיבורים.",
  howToGetMeta: "איך משיגים את הפרטים?",
  metaStep1: "צור אפליקציית Meta (סוג Business) ב-developers.facebook.com והוסף את מוצרי WhatsApp + Facebook Login for Business.",
  metaStep2: "השלם אימות עסק (Business Verification) ובקש Advanced Access להרשאות whatsapp_business_management + whatsapp_business_messaging.",
  metaStep3: "צור תצורת Embedded Signup (מקבל config_id), והגדר את כתובת ה-Webhook + Verify Token באפליקציה.",
  metaAppId: "App ID",
  metaAppSecret: "App Secret",
  metaConfigId: "Embedded Signup Config ID",
  metaVerifyToken: "Webhook Verify Token",
  metaGraphVersion: "Graph API Version (למשל v21.0)",

  // bot readiness status
  statusLive: "הבוט פעיל ועונה ללקוחות",
  statusLiveHint: "שלח/י הודעת בדיקה למספר המחובר כדי לראות את הבוט בפעולה.",
  statusNoNumber: "אין מספר וואטסאפ מחובר",
  statusNoNumberHint: "חבר/י מספר (סריקת QR) כדי שהבוט יתחיל לעבוד.",
  statusNoFlow: "מחובר — אבל אין בוט פעיל",
  statusNoFlowHint: "הפעל/י תסריט כדי שהבוט יתחיל לענות ללקוחות.",
  statusConnectNumber: "לחיבור מספר",
  statusActivateFlow: "להפעלת בוט",
  statusTestNumber: "שלח/י הודעת בדיקה אל",

  // connections
  connectionsTitle: "חיבורי וואטסאפ",
  connectionsSubtitle: "חבר/י מספר וואטסאפ כדי שהבוט יתחיל לענות ללידים",
  addConnection: "הוסף חיבור",
  connectionLabel: "כינוי לחיבור (למשל: קו מכירות)",
  create: "צור",
  scanQr: "סרוק/י את הקוד באפליקציית וואטסאפ ← מכשירים מקושרים ← קישור מכשיר",
  waiting: "ממתין לקוד…",
  connect: "חבר",
  reconnect: "חבר מחדש",
  disconnect: "נתק",
  backToDashboard: "→ חזרה ללוח הבקרה",
  noConnections: "עדיין אין חיבורים. הוסף/י אחד כדי להתחיל.",
  statusLabel: {
    PENDING: "ממתין",
    QR: "ממתין לסריקה",
    CONNECTED: "מחובר",
    DISCONNECTED: "מנותק",
    LOGGED_OUT: "נותק מהמכשיר",
  },

  // cloud api (official WhatsApp)
  providerBaileys: "חיבור מהיר (QR)",
  providerCloud: "WhatsApp רשמי (Cloud API)",
  cloudDesc: "החיבור הרשמי של Meta — יציב ומאושר לשימוש עסקי בקנה מידה. דורש חשבון WhatsApp Business.",
  cloudPhoneId: "Phone Number ID",
  cloudToken: "Access Token (מוצפן)",
  cloudVerify: "Verify Token (אופציונלי — ייווצר אוטומטית)",
  cloudCreate: "חבר Cloud API",
  cloudWebhookTitle: "כתובת Webhook להגדרה ב-Meta",
  cloudWebhookHint: "הדבק/י את הכתובת הזו + ה-Verify Token בהגדרות ה-Webhook של אפליקציית ה-Meta שלך.",
  cloudViaLabel: "רשמי (Cloud API)",

  // embedded signup (one-click official onboarding)
  esTitle: "חיבור רשמי בלחיצה אחת",
  esDesc: "התחבר/י עם פייסבוק ו-Meta תיצור עבורך את חשבון ה-WhatsApp Business, המספר והאישורים — אוטומטית.",
  esButton: "התחברות עם פייסבוק",
  esConnecting: "מתחבר…",
  esRecommended: "מומלץ",
  esAdvanced: "הזנה ידנית (מתקדם)",
  esCancelled: "החיבור לא הושלם. אפשר לנסות שוב.",
  esFailed: "החיבור נכשל. בדוק/י את הפרטים ונסה/י שוב.",
  esNotConfigured: "החיבור הרשמי עדיין לא הוגדר על ידי מנהל המערכת.",
  esSuccess: "המספר חובר בהצלחה! 🎉",

  // leads / CRM
  leadsTitle: "לידים",
  leadsSubtitle: "כל מי שכתב לבוט — עם התשובות שנאספו",
  searchLeads: "חיפוש לפי שם או טלפון…",
  noLeads: "עדיין אין לידים. ברגע שמישהו יכתוב לבוט הוא יופיע כאן.",
  colName: "שם",
  colPhone: "טלפון",
  colTags: "תגיות",
  colCreated: "נוצר",
  colFields: "תשובות",
  colSource: "מקור",
  sourceScenario: "מתסריט",
  sourceNone: "הודעה בלבד",
  filterScenarioOnly: "רק לידים מתסריט",
  filterAll: "הכול",
  backToLeads: "→ חזרה ללידים",
  leadDetails: "פרטי ליד",
  collectedFields: "תשובות שנאספו",
  transcript: "שיחה",
  noMessages: "אין הודעות עדיין",
  appointmentsTitle: "פגישות",
  appointmentsSubtitle: "פגישות מכירה שנקבעו דרך הבוט",
  noAppointments: "אין פגישות",
  upcoming: "הקרובות",
  past: "עברו",
  msgIn: "ליד",
  msgOut: "בוט",

  // settings / integrations
  settings: "הגדרות",
  settingsTitle: "הגדרות ואינטגרציות",
  googleCalendar: "יומן Google",
  googleCalendarDesc: "סנכרון דו־כיווני: פגישות שנקבעות ייווצרו ביומן, ושעות תפוסות יחסמו מהצעת מועדים.",
  connectGoogle: "חבר/י יומן Google",
  disconnectGoogle: "נתק יומן",
  googleConnected: "יומן Google מחובר ✅",
  googleNotConfigured: "אינטגרציית Google לא הוגדרה בשרת (חסר GOOGLE_CLIENT_ID/SECRET).",
  googleSetupHint:
    "כדי להפעיל: צרו OAuth Client ב-Google Cloud Console (APIs & Services → Credentials → Create OAuth client ID → Web application), הוסיפו את כתובת ה-Redirect למטה, והזינו את ה-Client ID וה-Secret בקובץ ‎.env‎ בשרת (GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET). כל בעל עסק מחבר את היומן שלו מכאן.",
  googlePerUserHint: "כל משתמש מחבר את היומן האישי שלו — פגישות של ליד ייכנסו ליומן של האחראי עליו.",
  googleConnectedMsg: "היומן חובר בהצלחה!",
  googleErrorMsg: "החיבור נכשל, נסה/י שוב.",
  remindersTitle: "תזכורות",
  remindersDesc: "לפני כל פגישה נשלחות ללקוח תזכורות אוטומטיות בוואטסאפ (24 שעות ושעה לפני).",

  // automatic follow-ups
  followUpsTitle: "פולו-אפ אוטומטי ללידים קרים",
  followUpsDesc: "הבוט ישלח תזכורת בוואטסאפ לליד שהפסיק לענות — כדי שאף ליד לא ילך לאיבוד.",
  followUpEnabledLabel: "הפעל פולו-אפ אוטומטי",
  followUpAfterHoursLabel: "אחרי כמה שעות שקט לשלוח",
  followUpMaxLabel: "מקסימום פולו-אפים לליד",
  followUpMessageLabel: "נוסח ההודעה",
  followUpMessageHint: "אפשר להשתמש ב-{name} כדי לשלב את שם הליד.",
  followUpDefaultMessage: "היי{name}, ראיתי שלא סיימנו את השיחה 🙂 אשמח לעזור אם עדיין רלוונטי!",
  followUpsSaved: "הגדרות הפולו-אפ נשמרו ✅",

  // broadcasts (רשימות תפוצה מתוזמנות)
  broadcasts: "רשימות תפוצה",
  broadcastsTitle: "רשימות תפוצה מתוזמנות",
  broadcastsSubtitle: "שליחת הודעה יזומה לרשימת אנשי קשר — מיד או במועד מתוזמן",
  newBroadcast: "רשימת תפוצה חדשה",
  noBroadcasts: "אין רשימות תפוצה עדיין",
  broadcastName: "שם הקמפיין",
  broadcastMessage: "נוסח ההודעה",
  broadcastMessageHint: "אפשר להשתמש ב-{name} כדי לשלב את שם הנמען.",
  broadcastWhen: "מתי לשלוח",
  broadcastNow: "שליחה מיידית",
  broadcastAt: "במועד מתוזמן",
  broadcastAudience: "נמענים",
  broadcastAudienceLeads: "לידים מהמערכת",
  broadcastAudienceLeadsAll: "כל הלידים",
  broadcastAudienceManual: "מספרים ידניים (מופרדים בפסיק או שורה)",
  broadcastAudienceCsv: "ייבוא מקובץ CSV",
  broadcastCsvHint: "עמודה ראשונה: טלפון. עמודה שנייה (אופציונלי): שם. שורת כותרת מזוהה אוטומטית.",
  broadcastCreate: "יצירת רשימת תפוצה",
  broadcastCancel: "ביטול שליחה",
  broadcastRecipients: "נמענים",
  broadcastNoRecipients: "לא נבחרו נמענים — הוסיפו לידים, מספרים או קובץ CSV.",
  broadcastStatus: {
    DRAFT: "טיוטה",
    SCHEDULED: "מתוזמן",
    SENDING: "בשליחה",
    SENT: "נשלח",
    CANCELLED: "בוטל",
  },
  recipientStatus: {
    PENDING: "ממתין",
    SENT: "נשלח",
    FAILED: "נכשל",
  },
  broadcastSafetyNote:
    "ההודעות נשלחות בהדרגה (כ-3 שניות בין הודעה להודעה) כדי להגן על המספר שלכם מחסימה. שליחה המונית למספרים שלא הסכימו לקבל הודעות עלולה לגרום לחסימת המספר על ידי וואטסאפ.",
  broadcastWaitingForConnection: "ממתין לחיבור וואטסאפ פעיל",

  // whatsapp groups
  groups: "קבוצות וואטסאפ",
  groupsTitle: "יצירת קבוצת וואטסאפ",
  groupsSubtitle: "יצירת קבוצה חדשה וצירוף לידים או רשימת מספרים אליה",
  groupSubject: "שם הקבוצה",
  groupWelcome: "הודעת פתיחה (אופציונלי)",
  groupCreate: "צור קבוצה",
  groupCreated: "הקבוצה נוצרה ✅",
  groupAddedCount: "צורפו",
  groupFailedCount: "לא צורפו (הגבלת פרטיות)",
  groupNeedsConnection: "נדרש חיבור וואטסאפ פעיל (Baileys/QR) כדי ליצור קבוצה.",
  groupNotSupportedCloud: "יצירת קבוצות נתמכת רק בחיבור QR, לא בחיבור Cloud API.",

  // flow builder — delay step
  nodeKindDelay: "המתנה",
  nodeDescDelay: "ממתין פרק זמן ואז ממשיך (למשל לתזכורת המשך)",
  delayAmountLabel: "כמה זמן להמתין",
  delayUnitMinutes: "דקות",
  delayUnitHours: "שעות",
  delayUnitDays: "ימים",
  delayStepSummary: "ממתין",
  placeholdersHint: "טיפ: אפשר לשלב תשובות קודמות בהודעות עם {שם-שדה}, למשל {name}.",

  // cal.com webhook
  calcomWebhookTitle: "עדכון אוטומטי מ-Cal.com",
  calcomWebhookDesc:
    "כשלקוח קובע פגישה בקישור ה-Cal.com שלכם, הליד יעודכן אוטומטית לסטטוס \"נקבעה פגישה\" והפגישה תופיע במערכת. הגדירו Webhook בחשבון Cal.com → Settings → Developer → Webhooks:",
  calcomWebhookUrlLabel: "כתובת ה-Webhook (Subscriber URL)",
  calcomWebhookSecretLabel: "Secret (אותו ערך גם ב-Cal.com וגם כאן)",
  calcomWebhookSecretPlaceholder: "מחרוזת סודית שתמציאו",
  calcomWebhookSaved: "הגדרות ה-Webhook נשמרו ✅",
  calcomWebhookEvents: "אירועים לסימון ב-Cal.com: Booking Created, Booking Cancelled, Booking Rescheduled",

  // billing / plans
  billing: "מנוי ותשלום",
  billingTitle: "בחירת מסלול",
  choosePlanTitle: "ברוך/ה הבא/ה! בחר/י מסלול כדי להתחיל",
  choosePlanSubtitle: "אפשר להתחיל בחינם ולשדרג בכל עת. אחרי בחירת מסלול נמשיך להקמת הבוט.",
  currentPlan: "המסלול הנוכחי",
  perMonth: "לחודש",
  free: "חינם",
  choosePlan: "בחר/י מסלול",
  upgrade: "שדרג/י",
  growNotConfigured: "כדי לגבות תשלום צריך קודם לחבר את חשבון Grow שלך (ראה/י אשף ההקמה).",
  goToOnboarding: "לאשף ההקמה",
  featureLockedTitle: "היכולת הזו דורשת שדרוג מסלול",
  featureLockedBroadcasts: "תפוצות והקבצות ל-WhatsApp זמינות במסלול המקצועי.",
  featureLockedFollowups: "תזכורות אוטומטיות זמינות החל ממסלול בסיסי.",
  featureLockedCalendar: "סנכרון יומן Google זמין החל ממסלול בסיסי.",
  featureLockedCta: "שדרג/י מסלול",
  contactsLimitReached: "הגעתם למכסת הלידים במסלול הנוכחי. שדרגו כדי להוסיף עוד.",
  thankYouTitle: "התשלום התקבל 🎉",
  thankYouBody: "תודה שבחרת ב-GeniriBot! נשאר רק שלב אחד — פתיחת חשבון כדי להתחיל להקים את הבוט.",
  thankYouCta: "צור/י חשבון",
  thankYouHaveAccount: "כבר יש לך חשבון?",

  // secrets (secure paste)
  secretsTitle: "מפתחות סודיים (Grow)",
  secretsDesc: "המפתחות נשמרים מוצפנים בשרת (AES-256). לעולם לא נציג אותם שוב — רק 4 הספרות האחרונות.",
  growPageCode: "קוד עמוד (Page Code)",
  growUserId: "מזהה משתמש (User ID)",
  growApiKey: "מפתח API (אופציונלי)",
  saveSecret: "שמור מאובטח",
  secretSaved: "נשמר מוצפן ✅",
  secretSet: "מוגדר",
  secretNotSet: "לא הוגדר",
  removeSecret: "הסר",
  howToGetGrow: "איך משיגים את המפתחות?",
  growStep1: "היכנס/י לחשבון Grow שלך בכתובת grow.business ← הגדרות ← מפתחות / API.",
  growStep2: "העתק/י את \"קוד העמוד\" (Page Code) ואת \"מזהה המשתמש\" (User ID).",
  growStep3: "הדבק/י אותם כאן למטה ולחצ/י \"שמור מאובטח\". המפתחות מוצפנים ואינם נחשפים.",

  // onboarding
  onboarding: "אשף הקמה",
  onboardingTitle: "בואו נחבר את מערכת קביעת הפגישות שלך",
  onboardingIntro: "3 שלבים קצרים כדי שהבוט יתחיל לקבוע פגישות מכירה בוואטסאפ.",
  stepDone: "בוצע",
  stepTodo: "לביצוע",
  ob1Title: "1. חיבור מספר וואטסאפ",
  ob1Desc: "חבר/י את המספר שדרכו הלקוחות כותבים אליך.",
  ob1Cta: "לחיבור וואטסאפ",
  ob2Title: "2. הגדרת שעות פנויות",
  ob2Desc: "המערכת מציעה ללקוח מועדים פנויים לפי הזמינות שלך (כרגע: א׳–ה׳ 09:00–17:00).",
  ob3Title: "3. סנכרון יומן Google — אופציונלי",
  ob3Desc: "חבר/י יומן Google כדי שפגישות ייווצרו אוטומטית ושעות תפוסות ייחסמו.",
  ob3Cta: "לחיבור יומן",
  obFinish: "סיום — למרכז הבקרה",
  obConnected: "מחובר ✅",
  obHowItWorks: "איך זה עובד?",
  obFlow1: "לקוח שולח הודעה למספר שלך",
  obFlow2: "הבוט מזהה טריגר ומתחיל תסריט",
  obFlow3: "הבוט אוסף תשובות וקובע פגישה",
  obFlow4: "הכול מופיע מסודר בלוח הבקרה שלך",

  // onboarding wizard
  wizNext: "הבא",
  wizBack: "הקודם",
  wizSkip: "דלג/י",
  wizFinish: "סיום 🎉",
  wizStepOf: "שלב",
  wizOf: "מתוך",
  wizWelcomeTitle: "ברוכים הבאים ל-GeniriBot! 👋",
  wizWelcomeBody: "3 דקות הקמה והבוט שלך יתחיל לאסוף לידים ולקבוע פגישות בוואטסאפ. אפשר לדלג על כל שלב ולחזור אליו אחר כך.",
  wizStart: "בואו נתחיל →",
  wizWhatsappTitle: "חברו מספר וואטסאפ",
  wizWhatsappBody: "המספר שדרכו לקוחות כותבים אליכם. לחצו לחיבור וסרקו את ה-QR.",
  wizWhatsappCta: "לחיבור המספר",
  wizWhatsappOfficial: "חיבור רשמי (מומלץ)",
  wizWhatsappQr: "או חיבור מהיר עם QR",
  wizWhatsappDone: "מספר מחובר ✅",
  wizAvailTitle: "שעות פעילות לפגישות",
  wizAvailBody: "הבוט יציע ללקוחות מועדים פנויים לפי הזמינות שלכם (ברירת מחדל: א׳–ה׳ 09:00–17:00). אפשר לשנות בהמשך.",
  wizCalTitle: "איך לקבוע פגישות?",
  wizCalBody: "בחרו איך הבוט יקבע פגישות עם לקוחות.",
  wizCalInChat: "מועדים בתוך הצ׳אט (לפי שעות הפעילות)",
  wizCalInChatDesc: "הבוט מציע מספרים לבחירה וקובע ישירות בשיחה.",
  wizCalGoogle: "סנכרון יומן Google",
  wizCalGoogleDesc: "פגישות נוצרות אוטומטית ביומן, שעות תפוסות נחסמות.",
  wizCalCalcom: "קישור Cal.com משלכם",
  wizCalCalcomDesc: "הדביקו את קישור ההזמנה שלכם מ-Cal.com — הבוט ישלח אותו ללקוח.",
  calcomLinkLabel: "קישור Cal.com",
  calcomLinkPlaceholder: "https://cal.com/your-name/30min",
  calcomSaved: "הקישור נשמר ✅",
  wizDoneTitle: "הכול מוכן! 🚀",
  wizDoneBody: "הבוט שלכם מוכן. שלחו הודעת בדיקה למספר המחובר כדי לראות אותו בפעולה.",

  // flows
  flowsTitle: "בוטים (תסריטים)",
  flowsSubtitle: "התסריטים שהבוט מריץ מול לידים",
  noFlows: "אין תסריטים עדיין",
  active: "פעיל",
  inactive: "כבוי",
  colVersion: "גרסה",
  colSteps: "שלבים",
  editFlow: "עריכה",
  newFlow: "תסריט חדש",
  activate: "הפעל",
  deactivate: "כבה",
  backToFlows: "→ חזרה לתסריטים",
  renameFlow: "שינוי שם",
  flowNameLabel: "שם התסריט",
  saveName: "שמירה",
  cancel: "ביטול",
  deleteFlow: "מחיקה",
  deleteFlowConfirm: "למחוק את התסריט לצמיתות? לא ניתן לשחזר אותו.",

  // flow builder — trigger
  triggerTitle: "מתי הבוט מתחיל? (טריגר)",
  triggerDesc: "כל שיחה מתחילה מהודעה של הלקוח. בחר/י מה מפעיל את התסריט הזה.",
  triggerAny: "כל הודעה ראשונה",
  triggerKeyword: "מילות מפתח",
  triggerKeywordsLabel: "מילים שיפעילו (מופרדות בפסיק)",
  triggerKeywordsHint: "לדוגמה: מעוניין, פגישה, מחיר",
  startNodeTitle: "התחלה",
  startNodeAny: "מתחיל בכל הודעה",
  startNodeKeyword: "מתחיל אם ההודעה מכילה:",

  // flow builder — node kinds & help
  nodeKindMessage: "הודעה",
  nodeKindQuestion: "שאלה",
  nodeKindCondition: "תנאי",
  nodeKindAction: "פעולה",
  nodeDescMessage: "שולח טקסט ללקוח (בלי לחכות לתשובה)",
  nodeDescQuestion: "שואל שאלה ושומר את התשובה בכרטיס הליד",
  nodeDescCondition: "מפצל את המסלול לפי תשובה (כן / לא)",
  nodeDescAction: "מבצע פעולה: קביעת פגישה, התראה, תגית ועוד",
  addStep: "הוסף שלב",
  savesTo: "💾 נשמר לשדה",
  dragHint: "💡 גרור/י מנקודת החיבור בתחתית שלב אל שלב אחר כדי לחבר ביניהם",
  questionSaveHint: "התשובה של הלקוח תישמר בכרטיס הליד תחת שם השדה הזה ותופיע ב-CRM.",
  chooseWhatToAsk: "מה לשאול את הלקוח?",
  chooseFieldName: "לאיזה שדה לשמור? (למשל: name, phone, budget)",
  chooseAnswerType: "סוג התשובה הצפויה",
  chooseAction: "איזו פעולה לבצע?",

  // sequence builder (step-by-step)
  seqIntro: "בנה/י את השיחה שלב אחרי שלב. ככה היא תיראה ללקוח ←",
  seqEmpty: "עוד אין שלבים. הוסף/י את השלב הראשון 👇",
  addStepMenu: "הוסף שלב",
  stepMessageLabel: "הודעה",
  stepQuestionLabel: "שאלה",
  stepBookLabel: "קביעת פגישה",
  stepMessageDesc: "הבוט שולח הודעה (למשל: קישור ליומן)",
  stepQuestionDesc: "הבוט שואל שאלה ושומר את התשובה",
  stepBookDesc: "הבוט מציע ללקוח מועדים פנויים לפגישה",
  botSends: "הבוט שולח:",
  botAsks: "הבוט שואל:",
  saveAnswerTo: "שומר את התשובה בשדה (יופיע ב-CRM):",
  answerTypeLabel: "סוג התשובה",
  choicesLabel: "כפתורי בחירה (אופציונלי, מופרד בפסיק)",
  bookNote: "הבוט יציע אוטומטית מועדים פנויים לפי הזמינות שלך, יקבע פגישה וישלח אישור.",
  msgPlaceholder: "כתוב/י מה הבוט יאמר…",
  askPlaceholder: "מה לשאול את הלקוח?",
  fieldPlaceholder: "לדוגמה: name, city, budget",
  previewTitle: "תצוגה מקדימה",
  previewYouAnswer: "התשובה שלי…",
  moveUp: "למעלה",
  moveDown: "למטה",
  stepN: "שלב",
  whenStarts: "מתי השיחה מתחילה?",

  // flow builder
  saveFlow: "שמור והפעל",
  saved: "נשמר ✅",
  savedLive: "נשמר — הבוט פעיל ועונה ללקוחות! ✅",
  flowLive: "🟢 פעיל — הבוט עונה ללקוחות",
  flowOff: "⚪ כבוי — שמור/י כדי להפעיל את הבוט",
  saveError: "שגיאה",
  selectNode: "בחר/י שלב לעריכה",
  startNode: "שלב התחלה",
  endNode: "סיום",
  deleteNode: "מחק שלב",
  fMessage: "טקסט ההודעה",
  fPrompt: "טקסט השאלה",
  fField: "שם השדה (לשמירה)",
  fExpect: "סוג תשובה",
  fChoices: "אפשרויות (מופרדות בפסיק)",
  fWhen: "תנאי",
  fThen: "אם כן →",
  fElse: "אם לא →",
  fAction: "פעולה",
  fNext: "השלב הבא →",

  // lead pipeline
  colStatus: "סטטוס",
  colOwner: "אחראי",
  colUpdated: "עודכן",
  leadStatus: {
    NEW: "חדש",
    CONTACTED: "יצרנו קשר",
    QUALIFIED: "מתאים",
    MEETING_SET: "נקבעה פגישה",
    WON: "נסגר ✅",
    LOST: "לא רלוונטי",
  },
  unassigned: "לא משויך",
  assignOwner: "שיוך לאחראי",
  changeStatus: "שינוי סטטוס",

  // filters
  filters: "סינון",
  filterStatus: "סטטוס",
  filterOwner: "אחראי",
  filterScenario: "תסריט",
  filterTag: "תגית",
  filterFrom: "מתאריך",
  filterTo: "עד תאריך",
  sortLabel: "מיון",
  sortNewest: "החדשים ביותר",
  sortOldest: "הישנים ביותר",
  sortActivity: "פעילות אחרונה",
  sortUpdated: "עודכנו לאחרונה",
  applyFilters: "סנן",
  clearFilters: "נקה סינון",
  anyValue: "הכול",
  noResults: "לא נמצאו לידים שתואמים לסינון.",

  // bulk actions + export
  selectAll: "בחר/י הכול",
  selectedCount: "נבחרו",
  bulkAssign: "שייך ל…",
  bulkStatus: "שנה סטטוס ל…",
  bulkApply: "החל",
  bulkNothingSelected: "לא נבחרו לידים",
  exportCsv: "ייצוא ל-CSV",

  // pagination
  prevPage: "→ הקודם",
  nextPage: "הבא ←",
  showing: "מציג",
  of: "מתוך",

  // call summary (agent-entered after the sales call)
  callSummaryTitle: "סיכום שיחת מכירה",
  callSummaryHint: "מה סוכם בשיחה? הסיכום נשמר על הליד ונראה לכל הצוות.",
  callSummaryPlaceholder: "לדוגמה: מעוניין בחבילה המורחבת, לחזור אליו בשבוע הבא…",
  callSummarySave: "שמור סיכום",
  callSummaryEmpty: "עדיין לא נרשם סיכום שיחה.",
  callSummaryBy: "נרשם על ידי",

  // hidden (LID) numbers
  hiddenNumber: "מספר מוסתר",
  hiddenNumberHint:
    "הלקוח פנה דרך WhatsApp במצב מספר מוסתר, כך שוואטסאפ לא מוסרת את מספר הטלפון שלו. אפשר לענות לו בצ׳אט כרגיל. כדי לקבל מספר לחיוג, הוסף/י שאלה מסוג ״טלפון״ לתסריט.",
  waIdLabel: "מזהה וואטסאפ",
  callbackPhoneLabel: "טלפון לחיוג",

  // analytics
  funnelTitle: "משפך המכירות",
  funnelHint: "כמה לידים בכל שלב",
  byScenarioTitle: "ביצועים לפי תסריט",
  byAgentTitle: "עומס לפי נציג",
  colLeads: "לידים",
  colWon: "נסגרו",
  colWinRate: "אחוז סגירה",
  colOpen: "פתוחים",
  staleTitle: "לידים שמתקררים",
  staleHint: "לידים פתוחים שלא נגעו בהם יותר משבוע",
  staleView: "הצג לידים מתקררים ←",
  staleNone: "אין לידים מוזנחים — כל הכבוד! 🎉",
  filterStale: "רק לידים מתקררים",
  analyticsNoData: "אין מספיק נתונים עדיין.",

  // flow builder — team steps
  stepAssignLabel: "שיוך לנציג",
  stepAssignDesc: "משייך את הליד לאיש מכירות אוטומטית",
  stepNotifyLabel: "התראה לנציג",
  stepNotifyDesc: "שולח לנציג התראה על הליד החדש",
  stepTagLabel: "הוספת תגית",
  stepTagDesc: "מסמן את הליד בתגית לסינון מהיר",
  assignToLabel: "שייך אל",
  assignAuto: "אוטומטי — הנציג הפנוי ביותר",
  assignNote: "אם הליד כבר משויך, השלב לא ישנה את השיוך.",
  notifyNote: "ההתראה נשלחת בוואטסאפ לנציג (אם הוגדר לו טלפון להתראות), אחרת במייל.",
  tagToAdd: "התגית להוספה",
  previewSilentStep: "שלב פנימי — הלקוח לא רואה כלום",

  // tags
  tagsTitle: "תגיות",
  addTag: "הוסף תגית",
  tagPlaceholder: "לדוגמה: דחוף, VIP…",
  removeTag: "הסר תגית",
  noTags: "אין תגיות.",

  // agent notification
  notifyPhone: "טלפון להתראות",
  notifyPhoneHint: "מספר וואטסאפ לקבלת התראות על לידים חדשים. ריק = התראה במייל.",
  save: "שמור",

  // notes
  notesTitle: "הערות",
  addNote: "הוסף הערה",
  notePlaceholder: "הערה פנימית על הליד…",
  noNotes: "אין הערות עדיין.",
  deleteNote: "מחק",

  // activity timeline
  timelineTitle: "היסטוריית פעילות",
  noActivity: "אין פעילות עדיין.",
  byBot: "הבוט",
  activityKind: {
    LEAD_CREATED: "הליד נוצר",
    STATUS_CHANGED: "שינוי סטטוס",
    OWNER_ASSIGNED: "שיוך אחראי",
    NOTE_ADDED: "נוספה הערה",
    SUMMARY_SAVED: "נשמר סיכום שיחה",
    TAGS_CHANGED: "עודכנו תגיות",
    APPOINTMENT_BOOKED: "נקבעה פגישה",
    APPOINTMENT_CANCELLED: "הפגישה בוטלה",
    CONVERSATION_COMPLETED: "השיחה עם הבוט הסתיימה",
    FOLLOW_UP_SENT: "נשלח פולו-אפ אוטומטי",
  },

  // team / users
  team: "צוות",
  teamTitle: "ניהול צוות",
  teamSubtitle: "הוסף/י אנשי מכירות ונהל/י הרשאות",
  teamMembers: "חברי צוות",
  roleLabel: {
    OWNER: "בעלים",
    ADMIN: "מנהל",
    AGENT: "נציג",
  },
  roleHint: {
    OWNER: "גישה מלאה, כולל חיוב ומחיקת העסק.",
    ADMIN: "ניהול לידים, תסריטים, חיבורים וצוות.",
    AGENT: "עבודה על לידים בלבד.",
  },
  changeRole: "שנה תפקיד",
  removeMember: "הסר",
  removeMemberConfirm: "להסיר את חבר הצוות?",
  youBadge: "את/ה",
  inviteTitle: "הזמנת חבר צוות",
  inviteEmail: "אימייל (אופציונלי — לשליחה במייל)",
  inviteRole: "תפקיד",
  inviteCreate: "צור הזמנה",
  inviteLinkTitle: "קישור ההזמנה",
  inviteLinkHint: "העתק/י ושלח/י בוואטסאפ. הקישור חד־פעמי ותקף ל־7 ימים.",
  inviteEmailSent: "ההזמנה נשלחה גם במייל ✉️",
  inviteEmailFailed: "ההזמנה נוצרה, אך שליחת המייל נכשלה — אפשר להעתיק את הקישור.",
  invitesPending: "הזמנות ממתינות",
  inviteRevoke: "בטל",
  inviteExpiresAt: "בתוקף עד",
  noInvites: "אין הזמנות ממתינות.",
  acceptInviteTitle: "הצטרפות לצוות",
  acceptInviteSubtitle: "בחר/י סיסמה כדי להשלים את ההצטרפות",
  acceptInviteCta: "הצטרף/י לצוות",
  passwordTooShort: "הסיסמה חייבת להכיל לפחות 6 תווים.",
  inviteInvalid: "ההזמנה אינה תקפה או שכבר נוצלה.",
  inviteExpired: "תוקף ההזמנה פג. בקש/י הזמנה חדשה.",
  inviteEmailTaken: "כתובת המייל הזו כבר רשומה במערכת.",
  onlyOwnerCan: "רק בעלים או מנהל יכולים לבצע פעולה זו.",
  cannotRemoveSelf: "אי אפשר להסיר את עצמך.",
  cannotRemoveLastOwner: "חייב להישאר בעלים אחד לפחות.",

  // nav (mobile)
  openMenu: "תפריט",
  closeMenu: "סגירה",
} as const;

export type HeKey = keyof typeof he;
